### ISSUE TITLE
Hard Puzzle 4 Unsolvable

### ISSUE THREAD

**Issue by tomatosoupcan** [Creckeryop/PiCrest#1]
Was beginning to think it couldn't be done, ran it through an online solver and came to the same conclusion:

{"ver":[[6],[2,2],[1,1],[1,1],[1,1,1,1],[1,1,1],[1,1,1,1],[1,1,1,2,1],[3,3,1,1],[1,2,3,2,1],[2,2,1,2,1],[1,1,1,1,2],[1,1,1,2],[1,2,2],[1,1,2,4]],"hor":[[2,2,1],[1,2,2],[1,1],[1,5,1],[1,6],[1,2,2,2],[1,1,2,1],[1,3],[1,2,1,1],[1,2,2,1,1],[1,2,2,3],[1,7],[3,1],[4,1],[1]]}

http://a.teall.info/nonogram/

**Comment by Creckeryop** [comment]
https://github.com/Creckeryop/PiCrest/releases/tag/v1.11-1
